language: bash
services: docker

env:
  - LUA_VERSION=5.3 LUAROCKS_VERSION=3.2.0

script:
  - ./scripts/cibuild

deploy:
  - provider: script
    script: "scripts/cipublish"
    on:
      repo: rbreslow/docker-lua
      branch: master
