#!/bin/bash

set -e

if [[ -n "${CI}" ]]; then
    set -x
fi

set -u

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Build container images from templates.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        sed -e "s/%%LUA_VERSION%%/${LUA_VERSION}/" \
            -e "s/%%LUAROCKS_VERSION%%/${LUAROCKS_VERSION}/" \
            "Dockerfile.template" >Dockerfile

        docker \
            build -t "quay.io/rbreslow/lua:${LUA_VERSION}" .

        ./scripts/test

        docker images
    fi
fi
