name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        lua_version: ["5.1", "5.3"]
        luarocks_version: ["3.3.1"]
        variant: [alpine]
    env:
      DOCKER_BUILDKIT: 1
      LUA_VERSION: ${{ matrix.lua_version }}
      LUAROCKS_VERSION: ${{ matrix.luarocks_version }}
      VARIANT: ${{ matrix.variant }}
    steps:
      - uses: actions/checkout@v2

      - run: ./scripts/cibuild

      - run: ./scripts/cipublish
        if: github.ref == 'refs/heads/master'
        env:
          QUAY_USER: ${{ secrets.QUAY_USER }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
